src/Entity/Articles.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\ArticlesRepository;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=ArticlesRepository::class)
 * @ORM\Table(name="articles", indexes={@ORM\Index(columns={"title", "content"}, flags={"fulltext"})})
 */
class Articles
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categories;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created_at;    

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;
 
    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }


    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCategories(): ?Categorie
    {
        return $this->categories;
    }

    public function setCategories(?Categorie $categories): self
    {
        $this->categories = $categories;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
    


}

src/Form/ArticlesType.php
<?php

namespace App\Form;



use App\Entity\User;


use App\Entity\Articles;
use App\Entity\Categorie;
use Symfony\Component\Form\AbstractType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ArticlesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class)
            ->add('content', CKEditorType::class)
            ->add('categories', EntityType::class, [
                'class' => Categorie::class,
            ])
            ->add('Valider', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Articles::class,
        ]);
    }
}

src/Controller/Admin/ArticlesController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Articles;
use App\Form\ArticlesType;
use App\Repository\ArticlesRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


/**
* @Route("/admin/articles", name="admin_articles_")
* @package App\Controller\Admin
*/
class ArticlesController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(ArticlesRepository $articlesRepo): Response
    {
        return $this->render('admin/articles/index.html.twig', [
            'articles' => $articlesRepo->findAll()
        ]);
    }

    /**
     * @Route("/ajout", name="ajout")
     */
    public function ajoutArticles(Request $request)
    {
        
        $articles = new Articles;
        $form = $this->createForm(ArticlesType::class, $articles);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid() ) {
            $em = $this->getDoctrine()->getManager();
            $articles->setUser($this->getUser());
            $em->persist($articles);
            $em->flush();

            return $this->redirectToRoute('admin_articles_index');

        }

        return $this->render('admin/articles/ajout.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/modifier/{id}", name="modifier")
     */
    public function ModifArticles(Articles $articles, Request $request)
    {
        $form = $this->createForm(ArticlesType::class, $articles);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid() ) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($articles);
            $em->flush();

            return $this->redirectToRoute('admin_articles_index');

        }

        return $this->render('admin/articles/ajout.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/supprimer/{id}", name="supprimer")
     */
    public function supprimer(Articles $articles, Request $request)
    {
    
            $em = $this->getDoctrine()->getManager();
            $em->remove($articles);
            $em->flush();
            
            $this->addFlash('message', 'Article supprimé avec succès');

            return $this->redirectToRoute('admin_articles_index');
    }



}

src/Controller/ArticlesController.php
<?php

namespace App\Controller;

use App\Entity\Articles;
use App\Form\ArticlesType;
use App\Repository\ArticlesRepository;
use App\Repository\CommentaireRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


/**
 * @Route("/articles")
 */
class ArticlesController extends AbstractController
{
     /**
     * @Route("/", name="app_articles_index", methods={"GET"})
     */
    public function index(ArticlesRepository $articlesRepo): Response
    {

        $articles = $articlesRepo->findAll();

        return $this->render('articles/index.html.twig', [
            'articles' => $articles,
        ]);
    }

    /**
     * @Route("/recherche", name="app_articles_recherche", methods={"GET"})
     */
    public function recherche(Request $request, ArticlesRepository $articlesRepository, CommentaireRepository $cr): Response
    {
        $tag = $request->query->get('search');
        $searchArticles = $articlesRepository->searchArticlesByTag($tag);
        $searchCom = $cr->searchCommentsByTag($tag);
        // dd($searchAnnonce, $searchCom);
        return $this->render('articles/recherche.html.twig', [
            'articles' => $searchArticles,
            'commentaires'=> $searchCom,
        ]);
    }

    
}

templates/articles/index.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Articles
{% endblock %}

{% block body %}
	<div class="container mx-auto mt-5 ">

		<section class="border-bottom mb-4">
			<h1 class="articles_title">Liste des articles :
			</h1>
			<div class="row align-items-center mb-4">
				<div class="col-lg-6 text-center text-lg-start mb-3 m-lg-0">
					<div class="d-flex flex-start align-items-center">
						{% if app.user %}
							<img class="rounded-5 shadow-1-strong me-2" height="35" alt="" loading="lazy" src="{{ asset(image_path ~ app.user.avatar)}}" alt="avatar" width="45" height="45"/>
						</br>
						<span>
							Published by
						</span>
					</br>
					<div>
						<h6 class="fw-bold text-primary mt-2 mb-1 ms-2 ">{{ app.user.username }}</h6>
					</div>
				{% endif %}
			</div>
		</div>
		<div class="col-lg-6 text-center text-lg-end">
			<button type="button" class="btn btn-primary px-3 me-1" style="background-color: #3b5998;">
				<i class="fab fa-facebook-f"></i>
			</button>
			<button type="button" class="btn btn-primary px-3 me-1" style="background-color: #55acee;">
				<i class="fab fa-twitter"></i>
			</button>
			<button type="button" class="btn btn-primary px-3 me-1" style="background-color: #0082ca;">
				<i class="fab fa-linkedin"></i>
			</button>
			<button type="button" class="btn btn-primary px-3 me-1">
				<i class="fas fa-comments"></i>
			</button>
		</div>
	</div>
</section>
{% for article in articles %}

	<h2 class="image_articles text-primary mt-5">{{ article.title|raw }}</h2>
	<div class="container-fluid mx-auto mt-5" id="articles-{{article.id}}">
		<div class="img-fluid shadow-2-strong mb-4 image_articles">
			{{article.createdAt| date }}
		</br>
	</br>
</br>
{{ article.content|raw }}</div><hr></div>{% else %}pas d'article{% endfor %}</div><section class="go_up"><div class="position-relative"><a href="#" class=" btn btn-primary position-absolute bottom-0 end-0 me-5 mb-5">Go Up ⇧</a></div></section>{% endblock %}

templates/articles/recherche-ajax.html.twig
<script>
	/* appel à la méthode ajax qui va mettre en place le transfert de données vers la base de données 
			 */

// charger la page avant d'exécuter la méthode ajax
window.addEventListener("load", () => { // il prend l'élément de l'id ci-dessous cité et il applique l'événement "on" sur le boutton submit de cet élément
$("#form-search").on("submit", (evtSubmit) => { // cette méthode nous permet de ne pas applique le comportement habituel du bouton submit
evtSubmit.preventDefault();
// on applique la méthode ajax pour ce faire il faut des recettes
// url pour: envoyer la requête vers le serveur
// method "POST" est utilisée dans notre requête pour envoyer des données( si on ne précise pas c'est "GET" par défault)
// data: ce sont les données des champs du formulaire dans notre cas un seul champ avec le nom suivant : "commentaire[message]"
// datatype: retourne la réponse en format json
$.ajax({
url: "{{ path('app_articles_recherche') }}",
data: "search=" + $("#form-search [name='search']").val(),
dataType: "html",
// success est une méthode de ajax qui permet de récupérer les données envoyés du serveur dans notre cas les données reçues sont inclues "getData"
success: (getData) => {
// on élimine la class "d-none" dans l'élément html contenant id="card-comment"
// $("#card-comment").removeClass("d-none");
// on affiche getData soit les données récupérées du serveur dans l'élément html contenant id="comment"
$("#main").html(getData);
},
// en cas d'erreur, la méthode ajax "error" met en place le message d'erreur cité ci-dessous dans la console du navigateur
error: (jqXHR, status, error) => {
console.log("ERREUR AJAX", status, error);
}
});
});
});

</script>

templates/articles/recherche.html.twig
{% block body %}

	<h1 class="ms-5 text-decoration-underline">Les Résultats :</h1>
	<div class="container">
		<div class="raw text-center">
			<h1 class="fs-1 text-primary fst-italic mt-5 mb-5">Partie des articles</h1>
			{% for article in articles %}

				<div>
					<h1 class="fs-6">{{ article.title }}</h1>

					<p>{{ article.content|raw }}</p>
				</div>
			{% endfor %}
		</div>
		<hr class="my-5">
		<div class="raw text-center">
			<h1 class="fs-1 text-primary fst-italic mb-5">Partie des commentaires</h1>
			{% for commentaire in commentaires %}
				<div class="mb-5">
					<p class="font-weight-bold text-light ms-4 me-4">{{ commentaire.message }}
					</p>
					<p class="font-weight-bold text-light ms-4 me-4">
						posté le
						{{ commentaire.createdAT|date("m/d/Y H:i:s") }}
					</p>
					<hr>
				</div>
			{% endfor %}
		</div>
	{% endblock %}